### ISSUE TITLE
Add pinyin on web page.

### ISSUE THREAD

**Issue by michael-spb-gor** [benlieb/chinese_console_public#8]
Add pinyin on web page.
![Unity Timeline封装，方便动态设置Timeline控制对象和参数_linxinfa的专栏-CSDN博客 - Opera 2021-10-02 13 40 40](https://user-images.githubusercontent.com/58518427/135712921-c037e6e3-4ab6-4bea-8a12-ecab6f60e3d6.png)
It is very helpfull. 
Add button on console to add pining over wolrds on web page.
Thank you for great plugin! You the best )!

P.s. 
Plugin name from screen short: Add Pinyin - Chinese Zero to Hero Reader (Chrome/Opera)

**Comment by benlieb** [comment]
This is a great feature request. I had originally wanted to do this, but just never got around to it.

**Comment by benlieb** [comment]
@michael-spb-gor this is still something I'd like to do, but it's harder than one might thing. The hardest part would be segmenting the words, and then adding the HTML markup to show the pinyin.

For example the 西 in  东西 would have a neutral tone when followed by 东. Many characters have multiple pronunciations depending on context. In some contexts, it's actually hard to deduce word boundaries except by social context, because there are multiple valid segmentations. Perhaps somewhat rare, but it it makes the point that the problem isn't trivial. It would be a lot easier to treat every character individually, but you'd have a lot of "errors" in all likelyhood.

**Comment by michael-spb-gor** [comment]
In any case thank you for great plugin!

**Comment by benlieb** [comment]
@michael-spb-gor thank you. I'm rolling out some new features in the next couple of weeks. I just rolled out color themes, and stroke animations. The next feature will be a full backend website that will collaborate with the extension to manage word lists and export formats etc. After that probably pronunciations.

Since you appreciate the extension, and if you haven't already, would you mind leaving a rating and review? This seems to be an important factor for people being willing to try it out...

It's the "Review" tab of this page: 

https://chrome.google.com/webstore/detail/chinese-console-popup-dic/mekipefdgdacoicbibojhhjppiiaoidp?hl=en&authuser=0

**Comment by michael-spb-gor** [comment]
Sounds great! 

5 Stars and Review done. 
Thank you!
